### ISSUE TITLE
Saying interface vs. using a class

### ISSUE THREAD

**Issue by szepeviktor** [seferov/typhp#3]
```php
    private function analyseFunctionLike(Node\FunctionLike $functionLike): void
    {
        $name = $functionLike->name;
```

Hello!

Is it okay to typehint FunctionLike and expecting a class implementing that interface in `$functionLike`?

FunctionLike does not have a->name.

**Comment by andrewprofile** [comment]
Yes, you should always give typehint for an interface. As for the IDE, you can give in PHPDoc: 
```php
/**
 * @param  Node\FunctionLikeInterface | Node\FunctionLike $functionLike
*/
```
Or:
```php
private function analyseFunctionLike(Node\FunctionLikeInterface $functionLike): void
{
     /** @var Node\FunctionLike $functionLike */
     $name = $functionLike->name;
```

**Comment by szepeviktor** [comment]
Thank you. I've asked this question while using @phpstan

The above code is actually in the source

https://github.com/seferov/typhp/blob/ff79b2e633732a4039bc24b40a772a1fcca47996/src/Analyser.php#L70-L72

phpstan displayed an error for non-existent $name property
