### ISSUE TITLE
.

### ISSUE THREAD

**Issue by mikevandiepen** [seferov/typhp#9]
.

**Comment by seferov** [comment]
Hello,

Yes, actually I have. I don't have any project using PHP 7.4 yet but soon I will definitely have at least one.

Best,
Farhad

**Comment by mikevandiepen** [comment]
Good to know! If you need or want any help regarding the "property types" implementation I'd like to help you. I have no experience in writing any lib like this but I'm an avid php savage =)

**Comment by seferov** [comment]
Thank you. Any contributions are more than welcome. Actually it is a simple library based on https://github.com/nikic/PHP-Parser which is doing most of the job

**Comment by mikevandiepen** [comment]
From today on I'll be starting to play around with this library! I'll keep you posted if I make any progress in property type validation!

**Comment by mikevandiepen** [comment]
I've chosen not to work from a fork to see where I can take it myself, you can follow the progress here; https://github.com/Mediadevs/PHP74-Property-Type-Validation/issues
